# Generated by Django 4.2.5 on 2023-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller_Mecanico', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre_Categoria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
