# Generated by Django 4.2.5 on 2023-10-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taller_Mecanico', '0011_servicios_delete_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Nombre_Categoria',
            new_name='nombre',
        ),
    ]
